# Generated by Django 3.2 on 2021-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='type_app',
            field=models.IntegerField(choices=[(0, 'Обслуживание'), (1, 'Консультация')], default=0, null=True, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.IntegerField(choices=[(0, 'Непрочитанный'), (1, 'К исполнению'), (2, 'Выполненный')], default=0, null=True, verbose_name='Статус заявки'),
        ),
    ]
