# Generated by Django 3.2.4 on 2021-06-13 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0010_auto_20210613_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тема заявки')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата решения')),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], null=True, verbose_name='Приоритет')),
                ('status', models.IntegerField(choices=[(0, 'Непрочитанный'), (1, 'К исполнению'), (2, 'Выполненный')], default=0, null=True, verbose_name='Статус заявки')),
                ('type_app', models.IntegerField(choices=[(0, 'Обслуживание'), (1, 'Консультация')], default=0, null=True, verbose_name='Тип заявки')),
                ('done_work', models.TextField(blank=True, null=True, verbose_name='Проделанная работа')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.applications', verbose_name='Заявка')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.clients', verbose_name='Клиент')),
                ('report_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший отчет')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.itperson', verbose_name='Ответсвтенный сотрудник')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['status'],
            },
        ),
    ]
