# Generated by Django 3.2.4 on 2021-06-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.applications', unique=True, verbose_name='Заявка'),
        ),
    ]
